# Default values for mongo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mongo
 

service:
  type: ClusterIP
  port: 27017
  targetPort: 27017

resources: 
  limits:
    cpu: 500m
    memory: 128Mi 
  requests:
     cpu: 100m
     memory: 128Mi

selector: 
  app: db-service


ports:
  containerPort: 27017