apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: studentapp
  name: student-deplyment
  namespace: student
spec:
  replicas: 1
  selector:
    matchLabels:
      app: studentapp
  template:
    metadata:
      labels:
        app: studentapp
    spec:
      containers:
      - image: studentdata
        name:  studentappimage 
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: studentapp


