apiVersion: v1
kind: Service
metadata:
  labels:
    app: studentapp
  name: studentapp
  namespace: student
spec:
  type: LoadBalancer
  ports:
  - name: app-service
    port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: studentapp
