apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.selector.app }}
  name: db-deplyment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app }}
    spec:
      volumes:
        - name: volume 
          persistentVolumeClaim:
            claimName: claim
      containers:
      - image: {{ .Values.image.repository }}
        name: mongo
        resources:
          limits:
            memory: {{ .Values.resources.limits.memory}}
            cpu: {{ .Values.resources.limits.cpu}}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /students
            port: 3000
        volumeMounts:
          - mountPath: /data/db/
            name: volume
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongosecret 
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongosecret
                key: password
















