apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: db-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: db-service
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: db-service
