apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.selector.app}}
  name: student-deplyment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selector.app}}
  template:
    metadata:
      labels:
        app: {{ .Values.selector.app}}
    spec:
      containers:
      - image: {{ .Values.image.repository }}
        name:  studentappimage 
        resources:
          limits:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          name: studentapp
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /students
            port: 3000

